"""JAX geometry kernels for the PushT body and reward.

The T is represented as two rectangles with disjoint interiors.  Keeping the
rectangles separate lets us compute the exact union intersection area using
four fixed-size convex-polygon intersections, which compiles cleanly with XLA.
"""

from __future__ import annotations

import jax
import jax.numpy as jnp

Array = jax.Array

WINDOW_SIZE = 512.0
TEE_CENTER_OF_GRAVITY = (0.0, 45.0)
TEE_AREA = 6_300.0

# Counter-clockwise vertices in the body-local frame used by Pymunk PushT.
_BAR_VERTICES = (
    (-60.0, 0.0),
    (60.0, 0.0),
    (60.0, 30.0),
    (-60.0, 30.0),
)
_STEM_VERTICES = (
    (-15.0, 30.0),
    (15.0, 30.0),
    (15.0, 120.0),
    (-15.0, 120.0),
)

# The concave exterior boundary, also counter-clockwise. Shared interior edges
# of the two rectangles are intentionally absent.
_TEE_VERTICES = (
    (-60.0, 0.0),
    (60.0, 0.0),
    (60.0, 30.0),
    (15.0, 30.0),
    (15.0, 120.0),
    (-15.0, 120.0),
    (-15.0, 30.0),
    (-60.0, 30.0),
)

# Nine block keypoints generated by the public Diffusion Policy PushT
# farthest-point sampler (seed=0). These reproduce the 20-value low-dimensional
# observation: 9 (x, y) block keypoints followed by the agent position.
_DIFFUSION_POLICY_LOCAL_KEYPOINTS = (
    (9.269786714, 90.040973524),
    (-60.983472364, -1.186729761),
    (60.912755577, -1.393364224),
    (-0.270503439, 25.543624991),
    (-14.064927576, 122.815853554),
    (39.002738500, 32.857404277),
    (-39.966414425, 32.729655446),
    (-16.824344379, 62.863178922),
    (23.541461220, -1.700288109),
)


def rotation_matrix(angle: Array) -> Array:
    """Return the 2-D counter-clockwise rotation matrix for ``angle``."""
    cosine = jnp.cos(angle)
    sine = jnp.sin(angle)
    return jnp.array(((cosine, -sine), (sine, cosine)), dtype=jnp.float32)


def transform_points(points: Array, position: Array, angle: Array) -> Array:
    """Transform body-local points into world coordinates."""
    return points @ rotation_matrix(angle).T + position


def inverse_transform_points(points: Array, position: Array, angle: Array) -> Array:
    """Transform world points into body-local coordinates."""
    return (points - position) @ rotation_matrix(angle)


def tee_rectangles(position: Array, angle: Array) -> Array:
    """Return both transformed T rectangles with shape ``(2, 4, 2)``."""
    local = jnp.asarray((_BAR_VERTICES, _STEM_VERTICES), dtype=jnp.float32)
    return transform_points(local, position, angle)


def tee_vertices(position: Array, angle: Array) -> Array:
    """Return the eight transformed exterior T vertices."""
    return transform_points(jnp.asarray(_TEE_VERTICES, dtype=jnp.float32), position, angle)


def tee_center_of_mass(position: Array, angle: Array) -> Array:
    """Convert the observable body origin to its physical center of mass."""
    cog = jnp.asarray(TEE_CENTER_OF_GRAVITY, dtype=jnp.float32)
    return transform_points(cog, position, angle)


def origin_from_center_of_mass(center: Array, angle: Array) -> Array:
    """Convert a physical center of mass to the observable body origin."""
    cog = jnp.asarray(TEE_CENTER_OF_GRAVITY, dtype=jnp.float32)
    return center - cog @ rotation_matrix(angle).T


def diffusion_policy_keypoints(
    block_position: Array, block_angle: Array, agent_position: Array
) -> Array:
    """Return the common 20-D Diffusion Policy low-dimensional observation."""
    local = jnp.asarray(_DIFFUSION_POLICY_LOCAL_KEYPOINTS, dtype=jnp.float32)
    block_keypoints = transform_points(local, block_position, block_angle)
    return jnp.concatenate((block_keypoints.reshape(-1), agent_position))


def _cross_2d(first: Array, second: Array) -> Array:
    return first[..., 0] * second[..., 1] - first[..., 1] * second[..., 0]


def _points_in_convex_polygon(points: Array, polygon: Array) -> Array:
    edges = jnp.roll(polygon, -1, axis=0) - polygon
    relative = points[:, None, :] - polygon[None, :, :]
    return jnp.all(_cross_2d(edges[None, :, :], relative) >= -1e-5, axis=1)


def _edge_intersections(first: Array, second: Array) -> tuple[Array, Array]:
    """Return all 16 pairwise rectangle edge intersections and valid mask."""
    first_delta = jnp.roll(first, -1, axis=0) - first
    second_delta = jnp.roll(second, -1, axis=0) - second

    starts_a = jnp.broadcast_to(first[:, None, :], (4, 4, 2))
    starts_b = jnp.broadcast_to(second[None, :, :], (4, 4, 2))
    directions_a = jnp.broadcast_to(first_delta[:, None, :], (4, 4, 2))
    directions_b = jnp.broadcast_to(second_delta[None, :, :], (4, 4, 2))

    offset = starts_b - starts_a
    denominator = _cross_2d(directions_a, directions_b)
    safe_denominator = jnp.where(jnp.abs(denominator) > 1e-7, denominator, 1.0)
    t = _cross_2d(offset, directions_b) / safe_denominator
    u = _cross_2d(offset, directions_a) / safe_denominator
    valid = (
        (jnp.abs(denominator) > 1e-7)
        & (t >= -1e-6)
        & (t <= 1.0 + 1e-6)
        & (u >= -1e-6)
        & (u <= 1.0 + 1e-6)
    )
    points = starts_a + t[..., None] * directions_a
    return points.reshape(16, 2), valid.reshape(16)


def convex_intersection_area(first: Array, second: Array) -> Array:
    """Compute the exact intersection area of two convex quadrilaterals.

    Candidate vertices consist of contained corners and edge intersections.
    Sorting the fixed 24-candidate array around its centroid avoids dynamic
    shapes and makes the routine JIT/vmap friendly.
    """
    edge_points, edge_valid = _edge_intersections(first, second)
    candidates = jnp.concatenate((first, second, edge_points), axis=0)
    valid = jnp.concatenate(
        (
            _points_in_convex_polygon(first, second),
            _points_in_convex_polygon(second, first),
            edge_valid,
        )
    )

    count = jnp.sum(valid.astype(jnp.int32))
    safe_count = jnp.maximum(count, 1)
    centroid = jnp.sum(jnp.where(valid[:, None], candidates, 0.0), axis=0) / safe_count
    angles = jnp.arctan2(candidates[:, 1] - centroid[1], candidates[:, 0] - centroid[0])
    angles = jnp.where(valid, angles, jnp.inf)
    order = jnp.argsort(angles)
    ordered = candidates[order]

    indices = jnp.arange(candidates.shape[0], dtype=jnp.int32)
    next_indices = jnp.mod(indices + 1, safe_count)
    cross_terms = _cross_2d(ordered, ordered[next_indices])
    twice_area = jnp.sum(jnp.where(indices < count, cross_terms, 0.0))
    return jnp.where(count >= 3, 0.5 * jnp.abs(twice_area), 0.0)


def coverage(
    block_position: Array,
    block_angle: Array,
    goal_position: Array,
    goal_angle: Array,
) -> Array:
    """Return the exact fraction of the goal T covered by the block T."""
    block_rectangles = tee_rectangles(block_position, block_angle)
    goal_rectangles = tee_rectangles(goal_position, goal_angle)

    def rectangle_pair(index: Array) -> Array:
        block_index = index // 2
        goal_index = index % 2
        return convex_intersection_area(block_rectangles[block_index], goal_rectangles[goal_index])

    intersection = jnp.sum(jax.vmap(rectangle_pair)(jnp.arange(4)))
    return jnp.clip(intersection / TEE_AREA, 0.0, 1.0)


def point_in_tee(local_points: Array) -> Array:
    """Test points already expressed in the T body-local frame."""
    x = local_points[..., 0]
    y = local_points[..., 1]
    in_bar = (x >= -60.0) & (x <= 60.0) & (y >= 0.0) & (y <= 30.0)
    in_stem = (x >= -15.0) & (x <= 15.0) & (y >= 30.0) & (y <= 120.0)
    return in_bar | in_stem
